CREATE TABLE project_types (
    project_type_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500)
);

CREATE TABLE project_type_phase_templates (
    project_type_phase_template_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_type_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    sequence_number NUMBER(6) NOT NULL,
    CONSTRAINT fk_ptpt_project_type
        FOREIGN KEY (project_type_id)
        REFERENCES project_types (project_type_id)
);

CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_type_id NUMBER NOT NULL,
    name VARCHAR2(150) NOT NULL,
    description VARCHAR2(500),
    start_date DATE,
    end_date DATE,
    CONSTRAINT fk_projects_project_type
        FOREIGN KEY (project_type_id)
        REFERENCES project_types (project_type_id)
);

CREATE TABLE phases (
    phase_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    sequence_number NUMBER(6) NOT NULL,
    start_date DATE,
    end_date DATE,
    CONSTRAINT fk_phases_project
        FOREIGN KEY (project_id)
        REFERENCES projects (project_id)
);

CREATE TABLE tasks (
    task_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id NUMBER NOT NULL,
    name VARCHAR2(150) NOT NULL,
    description VARCHAR2(1000),
    status VARCHAR2(30),
    CONSTRAINT fk_tasks_phase
        FOREIGN KEY (phase_id)
        REFERENCES phases (phase_id)
);

CREATE TABLE checklist_items (
    checklist_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id NUMBER NOT NULL,
    label VARCHAR2(200) NOT NULL,
    is_complete CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_checklist_items_task
        FOREIGN KEY (task_id)
        REFERENCES tasks (task_id)
);
