-- Initial Oracle DDL for Project Management System

CREATE TABLE project_type (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(200) NOT NULL,
  description VARCHAR2(1000)
);

CREATE TABLE project_type_phase_template (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_type_id NUMBER NOT NULL,
  name VARCHAR2(200) NOT NULL,
  default_order NUMBER,
  default_start_offset_days NUMBER,
  default_duration_days NUMBER,
  CONSTRAINT fk_ptpt_project_type
    FOREIGN KEY (project_type_id)
    REFERENCES project_type (id)
);

CREATE TABLE project (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_type_id NUMBER NOT NULL,
  name VARCHAR2(200) NOT NULL,
  description VARCHAR2(2000),
  start_date DATE,
  end_date DATE,
  CONSTRAINT fk_project_project_type
    FOREIGN KEY (project_type_id)
    REFERENCES project_type (id),
  CONSTRAINT chk_project_dates
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE phase (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL,
  name VARCHAR2(200) NOT NULL,
  start_date DATE,
  end_date DATE,
  order_index NUMBER,
  status VARCHAR2(50),
  CONSTRAINT fk_phase_project
    FOREIGN KEY (project_id)
    REFERENCES project (id),
  CONSTRAINT chk_phase_dates
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE task (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  phase_id NUMBER NOT NULL,
  title VARCHAR2(200) NOT NULL,
  description VARCHAR2(2000),
  start_date DATE,
  end_date DATE,
  status VARCHAR2(50),
  priority VARCHAR2(50),
  CONSTRAINT fk_task_phase
    FOREIGN KEY (phase_id)
    REFERENCES phase (id),
  CONSTRAINT chk_task_dates
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE checklist_item (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  task_id NUMBER NOT NULL,
  title VARCHAR2(200) NOT NULL,
  is_complete CHAR(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT fk_checklist_task
    FOREIGN KEY (task_id)
    REFERENCES task (id),
  CONSTRAINT chk_checklist_complete
    CHECK (is_complete IN ('Y', 'N'))
);

CREATE INDEX idx_ptpt_project_type_id ON project_type_phase_template (project_type_id);
CREATE INDEX idx_project_project_type_id ON project (project_type_id);
CREATE INDEX idx_phase_project_id ON phase (project_id);
CREATE INDEX idx_task_phase_id ON task (phase_id);
CREATE INDEX idx_checklist_task_id ON checklist_item (task_id);
